stages:
  - lint
  - test

lint:
  stage: lint
  image: python:3.10
  script:
    - pip install flake8
    - flake8 src tests

test:
  stage: test
  image: python:3.10
  script:
    - python -m unittest discover -s tests -v
